### ISSUE TITLE
✨[FEAT] Firebase Realtime Database 연결하기

### ISSUE THREAD

**Issue by lenamin** [lenamin/CreditCardList#1]
## 💡 Issue
Firebase Realtime Database 연결하기

## 📝  todo
- [x] 데이터 불러오기 
- [ ] 입력 기능 구현하기
- [ ] 수정 기능 구현하기
- [ ] 삭제  기능 구현하기
